export const IPC = {
  SCRAPE_RUN: "scrape:run",
  SCRAPE_LOG: "scrape:log",
  SCRAPE_BULK_RUN: "scrape:bulk-run",
  SCRAPE_BULK_PROGRESS: "scrape:bulk-progress",
  SCRAPE_BULK_CANCEL: "scrape:bulk-cancel",
  LOGIN_RUN: "login:run",
  OPEN_LOGS_FOLDER: "logs:open-folder",
  SENDER_CONFIG_GET: "sender-config:get",
  SENDER_CONFIG_SAVE: "sender-config:save",
  PROMPT_PREVIEW: "sender-config:prompt-preview",
  PROMPT_PREVIEW_REFERRAL: "sender-config:prompt-preview-referral",
  LEAD_CHECK_DUPLICATE: "lead:check-duplicate",
  LEAD_CREATE_FROM_SCRAPE: "lead:create-from-scrape",
  LEAD_LIST: "lead:list",
  LEAD_UPDATE_DRAFT: "lead:update-draft",
  LEAD_DELETE: "lead:delete",
  LEAD_BULK_DELETE: "lead:bulk-delete",
  LEAD_REGENERATE: "lead:regenerate",
  LEAD_REGENERATE_WITH_INSTRUCTION: "lead:regenerate-with-instruction",
  LEAD_SEND: "lead:send",
  LEAD_REFRESH_PROFILE: "lead:refresh-profile",
  LEAD_REFRESH_BOTH: "lead:refresh-both",
  LEAD_GENERATE_FOLLOWUP: "lead:generate-followup",
  LEAD_SEND_FOLLOWUP: "lead:send-followup",
  LEAD_CHECK_FOR_REPLIES: "lead:check-for-replies",
  LEAD_CHECK_ALL_REPLIES: "lead:check-all-replies",
  LEAD_MARK_COLD: "lead:mark-cold",
  LEAD_OVERDUE_COUNT: "lead:overdue-count",
  LEAD_SEND_REPLY: "lead:send-reply",
  LEAD_GENERATE_REPLY: "lead:generate-reply",
  LEAD_MARK_CONVERTED: "lead:mark-converted",
  LEAD_UPDATE_REPLIED: "lead:update-replied",
  LEAD_REOPEN: "lead:reopen",
  QUEUE_CANCEL: "queue:cancel",
  QUEUE_STATUS: "queue:status",
  QUEUE_PROGRESS: "queue:progress",
  QUEUE_DRAINED: "queue:drained",
  QUEUE_RETRY: "queue:retry",
  QUEUE_SESSION_EXPIRED: "queue:session-expired",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
